import os
from pathlib import Path
from google.auth.transport.requests import Request
from google.oauth2.credentials import Credentials
from google_auth_oauthlib.flow import InstalledAppFlow
from googleapiclient.discovery import build
from googleapiclient.http import MediaFileUpload
from instagrapi import Client
from instagrapi.exceptions import LoginRequired

from config import (
    BASE_DIR,
    DEFAULT_INSTAGRAM_CAPTION,
    DEFAULT_YOUTUBE_DESCRIPTION,
    INSTAGRAM_PASSWORD,
    INSTAGRAM_USERNAME,
    YOUTUBE_CLIENT_SECRETS_FILE,
    YOUTUBE_SCOPES,
)

YOUTUBE_TOKEN_FILE = BASE_DIR / "token.json"
IG_SESSION_FILE = BASE_DIR / "instagram_session.json"

# ---------------------------------------------------------------------------
# Platform: Instagram Reels
# ---------------------------------------------------------------------------


def get_instagram_client() -> Client:
    """Authenticate and return an instagrapi client session."""
    if not INSTAGRAM_PASSWORD:
        raise ValueError("INSTAGRAM_PASSWORD is not set in your .env file.")

    cl = Client()
    cl.delay_range = [1, 3]

    if IG_SESSION_FILE.exists():
        try:
            cl.load_settings(IG_SESSION_FILE)
            cl.login(INSTAGRAM_USERNAME, INSTAGRAM_PASSWORD)
            return cl
        except (LoginRequired, Exception) as e:
            print(f"Stored IG session expired or failed ({e}). Re-authenticating...")

    cl.login(INSTAGRAM_USERNAME, INSTAGRAM_PASSWORD)
    cl.dump_settings(IG_SESSION_FILE)
    return cl


def upload_instagram_reel(video_path: Path, caption: str = DEFAULT_INSTAGRAM_CAPTION) -> str:
    """Upload a video directly as an Instagram Reel."""
    print(f"Preparing Instagram Reel upload for: {video_path.name}")
    cl = get_instagram_client()

    media = cl.clip_upload(
        path=str(video_path),
        caption=caption,
    )

    # Clean up thumbnail generated by instagrapi
    for ext in [".mp4.jpg", ".jpg"]:
        thumb = video_path.with_name(f"{video_path.name}{ext}")
        if thumb.exists():
            thumb.unlink()

    media_id = str(media.pk)
    print(f"Instagram Reel successfully posted! Media ID: {media_id}")
    return media_id


# ---------------------------------------------------------------------------
# Platform: YouTube Shorts
# ---------------------------------------------------------------------------


def get_youtube_service():
    """Authenticate and return an authorized YouTube API service object with token caching."""
    creds = None

    if os.path.exists(YOUTUBE_TOKEN_FILE):
        creds = Credentials.from_authorized_user_file(
            str(YOUTUBE_TOKEN_FILE), YOUTUBE_SCOPES
        )

    if not creds or not creds.valid:
        if creds and creds.expired and creds.refresh_token:
            creds.refresh(Request())
        else:
            flow = InstalledAppFlow.from_client_secrets_file(
                YOUTUBE_CLIENT_SECRETS_FILE, scopes=YOUTUBE_SCOPES
            )
            creds = flow.run_local_server(port=0)

        with open(YOUTUBE_TOKEN_FILE, "w") as token:
            token.write(creds.to_json())

    return build("youtube", "v3", credentials=creds)


def upload_youtube_short(
    video_path: Path, title: str, description: str = DEFAULT_YOUTUBE_DESCRIPTION
) -> str:
    """Upload a local video as a YouTube Short using YouTube Data API v3."""
    youtube = get_youtube_service()

    full_title = f"{title} #Shorts" if "#Shorts" not in title else title
    full_desc = f"{description}\n\n#Shorts"

    body = {
        "snippet": {
            "title": full_title,
            "description": full_desc,
            "categoryId": "22",
        },
        "status": {
            "privacyStatus": "public",
            "selfDeclaredMadeForKids": False,
        },
    }

    media = MediaFileUpload(
        str(video_path), chunksize=-1, resumable=True, mimetype="video/mp4"
    )

    request = youtube.videos().insert(
        part="snippet,status", body=body, media_body=media
    )

    response = None
    while response is None:
        _, response = request.next_chunk()

    media_id = response.get("id", "")
    print(f"YouTube Short successfully posted! Video ID: {media_id}")
    return media_id